package javaprojeodevi;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//cxczownfownonw
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author UTKU
 */
public class AnaSayfa extends javax.swing.JFrame {

    /**
     * Creates new form AnaSayfa
     */
    /*private static final long serialVersionUID = 1L;
    
    public MainFrame(){
        super();
        this.setTitle();
        this.setUndecorated(true);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
    }*/
    public AnaSayfa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnList = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        lblKelimeUygulamasi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelime Ezberleme Uygulaması");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 408));
        getContentPane().setLayout(null);

        btnList.setBackground(new java.awt.Color(255, 204, 204));
        btnList.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnList.setText("Kelimeleri İşlemleri");
        btnList.setFocusPainted(false);
        btnList.setPreferredSize(new java.awt.Dimension(75, 32));
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });
        getContentPane().add(btnList);
        btnList.setBounds(100, 240, 280, 80);

        btnTest.setBackground(new java.awt.Color(255, 204, 204));
        btnTest.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnTest.setText("Kendini Test Et");
        btnTest.setMaximumSize(new java.awt.Dimension(247, 39));
        btnTest.setMinimumSize(new java.awt.Dimension(247, 39));
        btnTest.setPreferredSize(new java.awt.Dimension(75, 32));
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });
        getContentPane().add(btnTest);
        btnTest.setBounds(100, 340, 280, 80);

        lblKelimeUygulamasi.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        lblKelimeUygulamasi.setForeground(new java.awt.Color(51, 51, 255));
        lblKelimeUygulamasi.setText("KELİME EZBERLEME");
        lblKelimeUygulamasi.setPreferredSize(new java.awt.Dimension(236, 32));
        getContentPane().add(lblKelimeUygulamasi);
        lblKelimeUygulamasi.setBounds(40, 20, 730, 100);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Hakkında");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 440, 280, 80);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("UYGULAMASI");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 80, 350, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/anasayfa3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jLabel1ComponentRemoved(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1030, 740);

        setSize(new java.awt.Dimension(1038, 707));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        close();

        try {
            KelimeListeleSayfasi sayfa = new KelimeListeleSayfasi();
            sayfa.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AnaSayfa.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnListActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        close();
        try {
            if (Database.dbGetIdArray().size() < 4) {
                JOptionPane.showMessageDialog(this, "Kelime sayısı 4'den az olamaz...");
            } else {
                try {
                    TestSayfasi test;
                    Database.dbAddTestId();
                    test = new TestSayfasi();
                    test.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AnaSayfa.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(AnaSayfa.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        

    }//GEN-LAST:event_btnTestActionPerformed

    private void jLabel1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel1ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ComponentRemoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        HakkindaSayfasi sayfa2 = new HakkindaSayfasi();
        sayfa2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void init() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblKelimeUygulamasi;
    // End of variables declaration//GEN-END:variables

}
